# Default values for teamcity-build-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 0

image:
  repository: gcr.io/ajensen-1993/teamcity-build-agent
  pullPolicy: IfNotPresent
  tag: ""
  digest: ""

env:
- name: DOCKER_IN_DOCKER
  value: start

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

priorityClassName:

serviceAccount:
  name: teamcity-build-agent-sa

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  runAsUser: 0

service:
  type: ClusterIP
  port: 80

affinity: